fix problem when Beremiz is running without matiec installed
set matiec settings only once on first use of ProjectController class and give
user-friendly message on compilation about missing matiec
installation.


Traceback (most recent call last):
  File "Beremiz.py", line 197, in <module>
    beremiz.Start()
  File "Beremiz.py", line 192, in Start
    self.CreateApplication()
  File "Beremiz.py", line 130, in CreateApplication
    self.BackgroundInitialization()
  File "Beremiz.py", line 137, in BackgroundInitialization
    self.ImportModules()
  File "Beremiz.py", line 176, in ImportModules
    import BeremizIDE
  File
"BeremizIDE.py", line 76, in <module>
    from ProjectController import ProjectController, GetAddMenuItems,
MATIEC_ERROR_MODEL, ITEM_CONFNODE
  File
"ProjectController.py", line 177, in <module>
    iec2c_cfg = Iec2CSettings()
  File
"ProjectController.py", line 101, in __init__
    self.ieclib_c_path = self.findLibCPath()
  File
"ProjectController.py", line 135, in findLibCPath
    os.path.join(self.ieclib_path, "C"),
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'