fix wrong Row number in DiscoveryDialog.py that caused following traceback:
Traceback (most recent call last):
  File "/home/beremiz/beremiz/ProjectController.py", line 1536, in _Connect
    dialog = DiscoveryDialog(self.AppFrame)
  File "/home/beremiz/beremiz/dialogs/DiscoveryDialog.py", line 124, in __init__
    self._init_ctrls(parent)
  File "/home/beremiz/beremiz/dialogs/DiscoveryDialog.py", line 121, in _init_ctrls
    self._init_sizers()
  File "/home/beremiz/beremiz/dialogs/DiscoveryDialog.py", line 73, in _init_sizers
    self._init_coll_ButtonGridSizer_Growables(self.ButtonGridSizer)
  File "/home/beremiz/beremiz/dialogs/DiscoveryDialog.py", line 64, in _init_coll_ButtonGridSizer_Growables
    parent.AddGrowableRow(1)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 15343, in AddGrowableRow
    return _core_.FlexGridSizer_AddGrowableRow(*args, **kwargs)
PyAssertionError: C++ assertion "!m_rows || idx < (size_t)m_rows" failed at ../src/common/sizer.cpp(1967) in AddGrowableRow(): invalid row index