fix issue with sometimes wrong return code of ProcessLogger
As a result of wrong return code Beremiz gives folowing traceback:
Traceback (most recent call last):
  File "./Beremiz.py", line 850, in OnMenu
    getattr(self.CTR, method)()
  File "/home/developer/WorkData/PLC/beremiz/beremiz/ProjectController.py", line 925, in _Build
    IECGenRes = self._Generate_SoftPLC()
  File "/home/developer/WorkData/PLC/beremiz/beremiz/ProjectController.py", line 568, in _Generate_SoftPLC
    return self._Compile_ST_to_SoftPLC()
  File "/home/developer/WorkData/PLC/beremiz/beremiz/ProjectController.py", line 661, in _Compile_ST_to_SoftPLC
    C_files.remove("POUS.c")
ValueError: list.remove(x): x not in list

The problem is that both threads (for reading stdout and stderr) call self.Proc.poll(),
that updates internal returncode field. This call is done without any locking and the first thread gets correct result,
but other gets 0 as retval. If 0 gets thread, that afterwards calls callback finish, then wrong return code is returned
to the parent. Now only the thread with a callback polls for the return code, other thread just checked local value.

Additionally function spin() waits now until all threads finish reading their pipes, so the results are always correct.