fix bug that appears if datatype in the project tree is renamed to wrong name (keyword, existend type,...)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16765, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/expando.py", line 126, in _adjustCtrl
    numLines = self.GetNumberOfLines()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16710, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the TreeTextCtrl object has been deleted, attribute access no longer allowed.