fix issues in PLCOpenEditor with moving from wxWidgets 2.8 to 3.0
1)
./PLCOpenEditor.py:63: wxPyDeprecationWarning: Using deprecated class PySimpleApp.
  app = wx.PySimpleApp()

2)
./PLCOpenEditor.py:475: wxPyDeprecationWarning: Call to deprecated item.
  wx.InitAllImageHandlers()

3)
Traceback (most recent call last):
  File "./PLCOpenEditor.py", line 480, in <module>
    frame = PLCOpenEditor(None, fileOpen=fileOpen)
  File "./PLCOpenEditor.py", line 163, in __init__
    IDEFrame.__init__(self, parent)
  File "/tmp/f/beremiz/IDEFrame.py", line 657, in __init__
    self._init_ctrls(parent)
  File "/tmp/f/beremiz/IDEFrame.py", line 485, in _init_ctrls
    self._init_icon(prnt)
  File "/tmp/f/beremiz/IDEFrame.py", line 476, in _init_icon
    if self.icon:
AttributeError: 'PLCOpenEditor' object has no attribute 'icon'